### ISSUE TITLE
[bug] CircleCI linting command fails

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#2066]
**Describe the bug**

The [CircleCI lint commits](https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3578/workflows/d37b76e9-ce4f-4822-bea8-069cc04c67e3/jobs/22859) step is failing.

```
           ^
TSError: ⨯ Unable to compile TypeScript:
commitlint.config.ts:1:1 - error TS1208: 'commitlint.config.ts' cannot be compiled under '--isolatedModules' because it is considered a global script file. Add an import, export, or an empty 'export {}' statement to make it a module.

1 "use strict";
  ~~~~~~~~~~~~

    at createTSError (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1617:30)
    at Module.m._compile (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at require.extensions.<computed> (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1621:12)
    at Object.require.extensions.<computed> [as .ts] (/home/circleci/.npm/_npx/16d437951fea4b5e/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  name: 'TypeScriptCompileError',
  filepath: '/home/circleci/project/commitlint.config.ts'
}

Exited with code exit status 1

```

**Expected behaviour**

It passes ✅

**Comment by thisislawatts** [comment]
Doing some experiments on this PR https://app.circleci.com/pipelines/gh/ONEARMY/community-platform?branch=fix%2Fmoderation-how-to-buttons

**Comment by thisislawatts** [comment]
Looks like a job that previously passed now fails, something in the world outside changed... https://app.circleci.com/pipelines/github/ONEARMY/community-platform/3576/workflows/46fcb975-32a7-4d50-a34d-91dc265c86a8/jobs/22890

**Comment by thisislawatts** [comment]
Well, burnt through the time I have available. Will come back to try again a bit later. We can skip this step if there are any urgent changes to merge.

**Comment by davehakkens** [comment]
Feel free to play around and increase credits @thisislawatts. Useful thing to fix :)

**Comment by DavidK0508** [comment]
It looks like the issue you linked is related to an error that is occurring when you are running the npx commitlint command in a CircleCI workflow. From the error message that is shown in the issue, it appears that the TypeScript compiler is unable to compile the commitlint.config.ts file because it is not being treated as a module.

To fix this error, you will need to add an import, export, or an empty export {} statement to the commitlint.config.ts file to make it a module. Alternatively, you can remove the --isolatedModules flag from the TypeScript compiler options to allow global script files to be compiled.

It's also worth nothing that the npm WARN using --force Recommended protections disabled. warning message indicates that you are using the --force flag when running the npm i command. This flag can be dangerous as it bypasses some of the protections that npm has in place, so it's generally recommended to avoid using it if possible.

**Comment by thisislawatts** [comment]
Thanks @DavidK0508, that is an accurate summary of the error messages being displayed. The problem here however seems to be that this job was executing successfully up until ~7 days ago. So the challenge is to identify what change has occurred that now results in this error being thrown.

**Comment by thisislawatts** [comment]
This seems to have been resolved.
