### ISSUE TITLE
[bug] Unable to build project

### ISSUE THREAD

**Issue by richardrdev** [ONEARMY/community-platform#2867]
Saw this discussed in #2758 in a side discussion, but didn't see any resolution, hope this is the correct place to put this.

**Describe the bug**
Running into a typescript (or possibly webpack?) error while building project.  Have followed the local setup steps listed [here](https://github.com/ONEARMY/community-platform/blob/a8218030713876f1ce78a42eaec3816e33d1f7b9/CONTRIBUTING.md).  When running `yarn start`, the dev server starts properly, serving the page title and favicon, but the actual React app fails to build, and I am instead served an html temporary page.  As far as I can tell, the typescript error is causing the app to not build, and so an empty page is being served.

I see in the referenced issue that at least one other person has encountered this build error, so I figured it was worth posting an issue in case other people run into the same thing.

**Error Log**
```
[platform] Browserslist: caniuse-lite is outdated. Please run:
[platform]   npx update-browserslist-db@latest
[platform]   Why you should do it regularly: https://github.com/browserslist/update-db#readme
[platform] (node:10561) [DEP_WEBPACK_DEV_SERVER_ON_AFTER_SETUP_MIDDLEWARE] DeprecationWarning: 'onAfterSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[platform] (Use `node --trace-deprecation ...` to show where the warning was created)
[platform] (node:10561) [DEP_WEBPACK_DEV_SERVER_ON_BEFORE_SETUP_MIDDLEWARE] DeprecationWarning: 'onBeforeSetupMiddleware' option is deprecated. Please use the 'setupMiddlewares' option.
[platform] Starting the development server...
[platform]
[platform] TypeError: Cannot set property mark of #<Object> which has only a getter
[platform] TypeError: Cannot set property mark of #<Object> which has only a getter
[platform]     at Object.connectTypeScriptPerformance (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/profile/TypeScriptPerformance.js:12:36)
[platform]     at createTypeScriptReporter (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:40:49)
[platform]     at Object.<anonymous> (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:21:30)
[platform]     at Generator.next (<anonymous>)
[platform]     at /home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:8:71
[platform]     at new Promise (<anonymous>)
[platform]     at __awaiter (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:4:12)
[platform]     at /home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:19:88
[platform]     at Object.<anonymous> (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:23:38)
[platform]     at Generator.next (<anonymous>)
[platform] TypeError: Cannot set property mark of #<Object> which has only a getter
[platform] TypeError: Cannot set property mark of #<Object> which has only a getter
[platform]     at Object.connectTypeScriptPerformance (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/profile/TypeScriptPerformance.js:12:36)
[platform]     at createTypeScriptReporter (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/typescript-reporter/reporter/TypeScriptReporter.js:40:49)
[platform]     at Object.<anonymous> (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:21:30)
[platform]     at Generator.next (<anonymous>)
[platform]     at /home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:8:71
[platform]     at new Promise (<anonymous>)
[platform]     at __awaiter (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:4:12)
[platform]     at /home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/reporter/reporter-rpc/ReporterRpcService.js:19:88
[platform]     at Object.<anonymous> (/home/rbr-ubuntu/workspace/community-platform/node_modules/react-scripts/node_modules/fork-ts-checker-webpack-plugin/lib/rpc/RpcService.js:23:38)
[platform]     at Generator.next (<anonymous>)
[platform] DeprecationWarning: 'originalKeywordKind' has been deprecated since v5.0.0 and will no longer be usable after v5.2.0. Use 'identifierToKeywordKind(identifier)' instead.
[platform] Compiled successfully!
[platform]
[platform] You can now view one-army-community-platform in the browser.
[platform]
[platform]   Local:            http://localhost:3000
[platform]   On Your Network:  http://172.20.249.136:3000
[platform]
[platform] Note that the development build is not optimized.
[platform] To create a production build, use yarn build.
[platform]
[platform] webpack compiled successfully
```

**Additional context**

- Yarn version is 3.6.3
- Node Version is 18.17.1
- environment is WSL on windows 10:  Linux 5.15.90.1-microsoft-standard-WSL2 x86_64 x86_64
- However, same error happens when building in Windows 10, outside of WSL

Does anybody have an idea what could be causing this error?  I assume there's a local config issue, but I can't figure out what it could be.

**Comment by thisislawatts** [comment]
Thanks for the report @richardrdev, would you be able to share the console output from the browser?

**Comment by richardrdev** [comment]
```
bootstrap:27 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at ./src/config/config.ts (http://localhost:3000/static/js/bundle.js:14860:21)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:254672:33)
    at fn (http://localhost:3000/static/js/bundle.js:254950:21)
    at ./src/logger/index.ts (http://localhost:3000/static/js/bundle.js:15028:72)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:254672:33)
    at fn (http://localhost:3000/static/js/bundle.js:254950:21)
    at ./src/common/Error/handler.ts (http://localhost:3000/static/js/bundle.js:14609:65)
    at __webpack_require__ (http://localhost:3000/static/js/bundle.js:254672:33)
    at fn (http://localhost:3000/static/js/bundle.js:254950:21)
    at ./src/index.tsx (http://localhost:3000/static/js/bundle.js:14995:79)
```

**Comment by richardrdev** [comment]
Ah, this appears to be a chrome issue - localhost page opens just fine in Firefox.  For any other devs getting this issue, just use Firefox.  Or Edge, it appears to work fine in Edge as well.

For what it's worth, a quick google suggests that the issue with "localstorage" is caused by cookie settings being set to block third-party cookies.  However, I have the default settings (block third-party only in incognito), and even with the setting set to "Allow all Third-party cookies always", I'm still getting a blank page in Chrome.  Definitely an issue between chrome and this app's use of localstorage, and it seems to be specific to local dev.  Not sure what the exact cause is.

Discussions on StackOverflow do suggest that the issue might be related to calling localStorage from within an iframe.  Not sure if it's happening in an iframe here?

**Comment by benfurber** [comment]
This doesn't seem to be a wide spread issue so I think this issue can be closed for now.
