### ISSUE TITLE
[bug] Research Listing page

### ISSUE THREAD

**Issue by thisislawatts** [ONEARMY/community-platform#3278]
**Describe the bug**

When viewing the Research listing page locally, http://localhost:3000/research, the browser console includes the following error message. 

```
 at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:200471:7)
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Link
    at InternalLink (http://localhost:3000/static/js/bundle.js:225523:21)
    at Username (http://localhost:3000/static/js/bundle.js:227672:21)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Grid (http://localhost:3000/static/js/bundle.js:108137:20)
    at a
    at LinkWithRef (http://localhost:3000/static/js/bundle.js:200471:7)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Card
    at ResearchListItem (http://localhost:3000/static/js/ResearchList.chunk.js:236:5)
    at observerComponent (http://localhost:3000/static/js/bundle.js:159967:69)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:201749:5)
    at Routes (http://localhost:3000/static/js/bundle.js:202370:5)
    at Suspense
    at routes
    at ResearchModuleContainer (http://localhost:3000/static/js/bundle.js:18281:76)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at Main (http://localhost:3000/static/js/bundle.js:20789:5)
    at RenderedRoute (http://localhost:3000/static/js/bundle.js:201749:5)
    at Routes (http://localhost:3000/static/js/bundle.js:202370:5)
    at Suspense
    at Router (http://localhost:3000/static/js/bundle.js:202308:15)
    at BrowserRouter (http://localhost:3000/static/js/bundle.js:200359:5)
    at div
    at http://localhost:3000/static/js/bundle.js:27949:66
    at Box (http://localhost:3000/static/js/bundle.js:108044:64)
    at Flex (http://localhost:3000/static/js/bundle.js:108085:14)
    at Pages
    at ErrorBoundary (http://localhost:3000/static/js/bundle.js:15141:5)
    at ThemeProvider (http://localhost:3000/static/js/bundle.js:27979:64)
    at Provider (http://localhost:3000/static/js/bundle.js:160993:24)
    at observerComponent (http://localhost:3000/static/js/bundle.js:159967:69)
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Start the local development server for the application.
2. Navigate to the Research listing page by going to http://localhost:3000/research.
3. Open the browser's developer tools to access the console.

**Expected behaviour**
The Research listing page should load without any JavaScript errors in the console. All components on the page should function correctly, including links, layouts (grids, flexboxes), and any custom components like ResearchListItem.

**Comment by dcth628** [comment]
Happy to help with this one!

**Comment by V24039** [comment]
@thisislawatts I think similar issue was found in Questions listing page, there instead of link tag the Box onclick method is used with navigate
![image](https://github.com/ONEARMY/community-platform/assets/52736045/f3ce1fea-b78c-4cfa-8f32-c888878985b4)

I think a similar approach might resolve this issue.

**Comment by kimskovhusandersen** [comment]
I can grab this ticket [@ONEARMY/maintainers](https://github.com/orgs/ONEARMY/teams/maintainers).
