### ISSUE TITLE
Fix flaky function test

### ISSUE THREAD

**Issue by benfurber** [ONEARMY/community-platform#3304]
Often get something like this on the cloud function tests on CI.

```
 FAIL  src/aggregations/userNotifications.aggregations.spec.ts
  ● Console

    console.log
      [Admin Configuration] - emulator

      at Object.<anonymous> (src/Firebase/admin.ts:14:11)

    console.info
      {"severity":"INFO","message":"[emails_pending Seed] Starting"}

      at write (node_modules/firebase-functions/lib/logger/index.js:66:74)

    console.info
      {"severity":"INFO","message":"[emails_pending Seed] 1 update entries"}

      at write (node_modules/firebase-functions/lib/logger/index.js:66:74)

    console.info
      {"severity":"INFO","message":"[emails_pending Seed] Beginning batch commits"}

      at write (node_modules/firebase-functions/lib/logger/index.js:66:74)

    console.info
      {"severity":"INFO","message":"[emails_pending Seed] Elapsed time - 1047 ms"}

      at write (node_modules/firebase-functions/lib/logger/index.js:66:74)

  ● User Notifications Aggregation › Aggregates user notifications to collection

    expect(received).toEqual(expected) // deep equality

    - Expected  - 11
    + Received  +  1

    - Object {
    -   "user_1": Object {
    -     "_authID": "user_1",
    -     "emailFrequency": "weekly",
    -     "notifications": Array [
    -       Object {
    -         "_id": "notification_1",
    -       },
    -     ],
    -   },
    - }
    + Object {}

      70 |       userWithNotifications
      71 |     const { emailFrequency } = notification_settings
    > 72 |     expect(res.data()).toEqual({
         |                        ^
      73 |       user_1: { _authID, emailFrequency, notifications },
      74 |     })
      75 |   })

      at src/aggregations/userNotifications.aggregations.spec.ts:72:24
      at fulfilled (src/aggregations/userNotifications.aggregations.spec.ts:5:58)
```

**Comment by mariojsnunes** [comment]
I've looked into this, seems to be some kind of race condition that might also be affected by the order the tests run.

Maybe another option would be to test UserNotificationAggregation process function in isolation. This way we could also avoid all the firestore mock shenanigans.
I'll work on this.
