### ISSUE TITLE
[developer experience] Get rid of TypeErrors on build

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3569]
As a developer, I would like to not see some weird errors when starting the React app.

Steps to reproduce:
1. run `yarn install`
2. run `yarn build`
3. See errors
```
TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\profile\TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporter.js:40:49)    at Object.<anonymous> (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:4:12)
    at C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:19:88
    at Object.<anonymous> (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\rpc\RpcService.js:23:38)
    at Generator.next (<anonymous>)
TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\profile\TypeScriptPerformance.js:12:36)
    at createTypeScriptReporter (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\typescript-reporter\reporter\TypeScriptReporter.js:40:49)    at Object.<anonymous> (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:21:30)
    at Generator.next (<anonymous>)
    at C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:4:12)
    at C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\reporter\reporter-rpc\ReporterRpcService.js:19:88
    at Object.<anonymous> (C:\Users\test\Documents\community-platform\node_modules\react-scripts\node_modules\fork-ts-checker-webpack-plugin\lib\rpc\RpcService.js:23:38)
    at Generator.next (<anonymous>)
```

**Comment by benfurber** [comment]
YES PLEASE! Would love to see this problem fixed!

**Comment by evakill** [comment]
this is no longer happening (at least for me) - looks like the offending package `react-scripts` was removed [here](https://github.com/ONEARMY/community-platform/pull/3612)
will wait to close until @benfurber or @pizzaisdavid can confirm on their end

**Comment by pizzaisdavid** [comment]
Makes sense to me
