### ISSUE TITLE
[bug] changes to documentation are not going live

### ISSUE THREAD

**Issue by pizzaisdavid** [ONEARMY/community-platform#3667]
I think it might be related to this job failing: https://github.com/ONEARMY/community-platform/actions/workflows/docs-deploy.yml

**Comment by pizzaisdavid** [comment]
```
Error [PathError]: Failed to find .rc file at path: /home/runner/work/community-platform/community-platform/.env-cmdrc.js
    at Object.getRCFileVars (/home/runner/work/community-platform/community-platform/packages/documentation/node_modules/env-cmd/dist/parse-rc-file.js:18:27)
    at async getRCFile (/home/runner/work/community-platform/community-platform/packages/documentation/node_modules/env-cmd/dist/get-env-vars.js:65:25)
    at async Object.EnvCmd (/home/runner/work/community-platform/community-platform/packages/documentation/node_modules/env-cmd/dist/env-cmd.js:39:15)
    at async Object.CLI (/home/runner/work/community-platform/community-platform/packages/documentation/node_modules/env-cmd/dist/env-cmd.js:19:16)
```

:thinking: https://github.com/ONEARMY/community-platform/commit/df53a153e7237861651e403dea40a93774be13bb#diff-f949a98aa1af8823171983127520afabafb28d45ff3f25b4ee2f64eddb0a06db

**Comment by benfurber** [comment]
@goratt12 This might be why you had problems last week? So hopefully the fix you have locally can be deployed soon?

**Comment by goratt12** [comment]
@benfurber yeah exactly same error, I will post the fix with the new documentation suggestion.
the fix I found was changing the command but maybe recreating the deleted file will solve it too, just need to make sure it doesn't interfere with Vite.
